sudo: false
language: generic
branches:
  only:
  - master
matrix:
  include:
    - os: linux
      env: TEST_LANG='paper'
script: |
  if [[ $TEST_LANG == paper ]]
  then
    cd academic
    source build-paper.sh
  fi
addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
    - cv.pdf
    target-paths:
    - "downloads/"
